pub mod btree;
pub mod buffer_pool;
pub mod config;
pub mod errors;
pub mod index;
pub mod overflow;
pub mod page;
pub mod table;
pub mod traits;
pub mod types;
pub mod wal;

pub const KBYTES: usize = 1024;
pub(crate) const HEADER_SIZE: usize = 20;
pub(crate) const PAGE_RECORD_METADATA_SIZE: usize = 20;
pub(crate) const INDEX_HEADER_SIZE: usize = 24;
pub(crate) const INDEX_ENTRY_SIZE: usize = 20;
pub(crate) const OVERFLOW_HEADER_SIZE: usize = 16;
pub(crate) const OVERFLOW_REF_SIZE: usize = 16;
pub(crate) const OVERFLOW_THRESHOLD: usize = 256;
pub(crate) const BTREE_NODE_SIZE: usize = 8192;
pub(crate) const BTREE_NODE_HEADER_SIZE: usize = 3;
pub(crate) const BTREE_MAX_KEYS_PER_NODE: usize = 4;
pub(crate) const BTREE_HEADER_BLOCK_SIZE: usize = 8192;
